version: '3.8'

services:
  db:
    image: postgres:12
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_database
    ports:
      - "8085:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6459:6379"

volumes:
  postgres_data:
